# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('diptych', 'background', 'image'),
    ]
