# Generated by Django 1.11.16 on 2018-12-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
