# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-19 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


from cmsplugin_blocks.choices_helpers import (get_album_default_template,
                                              get_album_template_choices)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cmsplugin_blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_blocks_album', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('brief', models.TextField(blank=True, default='', verbose_name='Brief')),
                ('template', models.CharField(blank=True, choices=get_album_template_choices(), default=get_album_default_template(), help_text='Used template for content look.', max_length=100, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, max_length=255, null=True, upload_to='blocks/album/%y/%m', verbose_name='Image')),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_item', to='cmsplugin_blocks.Album')),
            ],
            options={
                'verbose_name': 'Album item',
                'verbose_name_plural': 'Album items',
            },
        ),
    ]
