# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-18 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cmsplugin_blocks', '0002_rename_diptych_background_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('hours', models.TextField(default='', verbose_name='Hours')),
            ],
            options={
                'verbose_name': 'Opening day item',
                'verbose_name_plural': 'Opening days items',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentOpening',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_blocks_establishmentopening', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Establishment opening',
                'verbose_name_plural': 'Establishment openings',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='slideitem',
            options={'verbose_name': 'Slide item', 'verbose_name_plural': 'Slide items'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='diptych',
            name='image',
            field=models.ImageField(default=None, max_length=255, null=True, upload_to='blocks/diptych/%y/%m', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='dayitem',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_item', to='cmsplugin_blocks.EstablishmentOpening'),
        ),
    ]
