# Generated by Django 2.1.9 on 2019-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blocks', '0002_add_slide_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideitem',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Title'),
        ),
    ]
