# Generated by Django 5.0.6 on 2024-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blocks', '0006_alter_card_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumitem',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Alternative image text'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Alternative image text'),
        ),
        migrations.AddField(
            model_name='container',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Alternative image text'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Alternative image text'),
        ),
        migrations.AddField(
            model_name='slideitem',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Alternative image text'),
        ),
    ]
