# Generated by Django 5.0.7 on 2024-08-29 01:31

import cmsplugin_blocks.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cmsplugin_blocks",
            "0011_accordion_alter_feature_plugins_accordionitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accordion",
            name="keep_open",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the already opened items are not closed when opening other items. On defaut, once an item is opened all other items are closed.",
                verbose_name="Keep items opened",
            ),
        ),
        migrations.AddField(
            model_name="accordionitem",
            name="opened",
            field=models.BooleanField(
                default=False,
                help_text="On default all accordion item are closed and need to be opened manually.This option enables this item to be initially opened.",
                verbose_name="Initially opened",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="plugins",
            field=cmsplugin_blocks.modelfields.CommaSeparatedStringsField(
                blank=True,
                choices=[
                    ("Accordion", "Accordion"),
                    ("Album", "Album"),
                    ("Card", "Card"),
                    ("Container", "Container"),
                    ("Hero", "Hero"),
                    ("Slider", "Slider"),
                ],
                default="",
                max_length=50,
                verbose_name="Allowed for plugins",
            ),
        ),
    ]
