# Generated by Django 5.0.9 on 2024-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsplugin_blocks", "0012_accordion_add_more_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="link_name",
            field=models.CharField(blank=True, max_length=45, verbose_name="link name"),
        ),
    ]
