# Generated by Django 4.2.15 on 2024-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_blocks', '0012_accordion_add_more_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Title'),
        ),
    ]
